#!/usr/bin/env python3
"""Shared schema constants for candidate main-report semantic contracts."""

from __future__ import annotations

ACTIONS = {
    "OPEN_POSITION", "TRIAL_POSITION", "ADD_POSITION", "HOLD", "HOLD_NO_ADD",
    "WATCH", "REVIEW", "REDUCE", "EXIT", "AVOID", "NO_ACTION", "UNKNOWN",
}
SCOPES = {"empty_position", "holder", "both", "unknown"}
INSTRUMENT_SCOPES = {"A_SHARE", "H_SHARE", "BOTH", "UNKNOWN"}
PRICE_ROLES = {
    "UNCONDITIONAL_ENTRY", "CONDITIONAL_ENTRY", "TRIAL_ENTRY", "REVIEW_ZONE",
    "WATCH_ZONE", "ADD_POSITION", "REDUCE_POSITION", "EXIT_ZONE",
    "VALUATION_REFERENCE", "FAIR_VALUE", "TARGET_PRICE", "SCENARIO_VALUE",
    "HISTORICAL_REFERENCE", "CURRENT_PRICE_REFERENCE", "NOT_ACTIONABLE", "UNKNOWN",
}
CONDITION_KINDS = {
    "ALL", "ANY", "AT_LEAST", "NOT", "PRICE_RANGE", "METRIC_COMPARE", "EVENT",
    "FILING", "DATE", "QUALITATIVE", "MANUAL_REVIEW", "UNKNOWN",
}
EFFECTS = {
    "ENTRY_GATE", "TRIAL_GATE", "ADD_GATE", "BLOCK_ENTRY", "BLOCK_ADD",
    "POSITIVE_TRIGGER", "NEGATIVE_TRIGGER", "REDUCE_TRIGGER", "EXIT_TRIGGER",
    "INVALIDATION", "MONITOR", "REVIEW_ONLY",
}
ENTRY_SEMANTICS = {
    "UNCONDITIONAL_ENTRY_DEFINED", "CONDITIONAL_ENTRY_DEFINED", "TRIAL_ENTRY_DEFINED",
    "REVIEW_ONLY", "EXPLICIT_NO_BUY", "NO_ENTRY_DEFINED", "AMBIGUOUS",
}
EVALUATION_STATES = {
    "BUY_READY", "TRIAL_READY", "PRICE_MATCHED_CONDITIONS_PENDING",
    "PRICE_MATCHED_CONDITIONS_NOT_MET", "CONDITIONS_MET_PRICE_PENDING",
    "PRICE_NOT_REACHED", "REVIEW_ZONE", "HARD_BLOCKED", "HARD_BLOCK_PENDING",
    "NO_ENTRY_PATH", "EXPLICIT_NO_BUY", "ENTRY_SEMANTIC_AMBIGUOUS",
    "NOT_EVALUATED",
}

SEMANTIC_STATUSES = {"ready", "partial", "ambiguous", "error"}
SCOPE_SEMANTIC_STATUSES = {"ready", "partial", "ambiguous"}
AMBIGUITY_CLASSIFICATIONS = {
    "ENTRY", "HOLDER", "EXIT_REDUCE", "MONITORING", "PATH_LOCAL", "GLOBAL",
}
SEMANTIC_REVIEW_REASONS = {
    "UNCONDITIONAL_ENTRY", "SCOPE_AMBIGUITY", "PRICE_ROLE_AMBIGUITY",
    "NESTED_LOGIC", "ANY_LOGIC", "AT_LEAST_N", "REPORT_CONTRACT_CONFLICT",
    "MULTI_MARKET", "ENTRY_AMBIGUOUS", "CROSS_SCOPE_DEPENDENCY",
    "UNRESOLVED_ACTION_MEANING", "NOT_LOGIC", "PATH_LOCAL_AMBIGUITY",
}
