#!/usr/bin/env python3
"""Shared schema constants for candidate main-report semantic contracts."""

from __future__ import annotations

ACTIONS = {
    "OPEN_POSITION", "TRIAL_POSITION", "ADD_POSITION", "HOLD", "HOLD_NO_ADD",
    "WATCH", "REVIEW", "REDUCE", "EXIT", "AVOID", "NO_ACTION", "UNKNOWN",
}
SCOPES = {"empty_position", "holder", "both", "unknown"}
INSTRUMENT_SCOPES = {"A_SHARE", "H_SHARE", "BOTH", "UNKNOWN"}
PRICE_ROLES = {
    "UNCONDITIONAL_ENTRY", "CONDITIONAL_ENTRY", "TRIAL_ENTRY", "REVIEW_ZONE",
    "WATCH_ZONE", "ADD_POSITION", "REDUCE_POSITION", "EXIT_ZONE",
    "VALUATION_REFERENCE", "FAIR_VALUE", "TARGET_PRICE", "SCENARIO_VALUE",
    "HISTORICAL_REFERENCE", "CURRENT_PRICE_REFERENCE", "NOT_ACTIONABLE", "UNKNOWN",
}
CONDITION_KINDS = {
    "ALL", "ANY", "AT_LEAST", "NOT", "PRICE_RANGE", "METRIC_COMPARE", "EVENT",
    "FILING", "DATE", "QUALITATIVE", "MANUAL_REVIEW", "UNKNOWN",
}
EFFECTS = {
    "ENTRY_GATE", "TRIAL_GATE", "ADD_GATE", "BLOCK_ENTRY", "BLOCK_ADD",
    "POSITIVE_TRIGGER", "NEGATIVE_TRIGGER", "REDUCE_TRIGGER", "EXIT_TRIGGER",
    "INVALIDATION", "MONITOR", "REVIEW_ONLY",
}
ENTRY_SEMANTICS = {
    "UNCONDITIONAL_ENTRY_DEFINED", "CONDITIONAL_ENTRY_DEFINED", "TRIAL_ENTRY_DEFINED",
    "REVIEW_ONLY", "EXPLICIT_NO_BUY", "NO_ENTRY_DEFINED", "AMBIGUOUS",
}
EVALUATION_STATES = {
    "BUY_READY", "TRIAL_READY", "PRICE_MATCHED_CONDITIONS_PENDING",
    "CONDITIONS_MET_PRICE_PENDING", "REVIEW_ZONE", "BLOCKED", "NO_ENTRY_PATH",
    "EXPLICIT_NO_BUY", "AMBIGUOUS", "NOT_EVALUATED",
}
